# Generated by Django 2.2.1 on 2022-07-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='company_different_services',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные сервисы компании'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='company_regions',
            field=models.TextField(blank=True, default='', verbose_name='Регионы, где есть филиал'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='company_site',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сайт компании'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='company_targeting',
            field=models.TextField(blank=True, default='', verbose_name='Средства  для расширения рынка сбыта и привлечения новых заказчиков'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='other_device_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание иного оборудования'),
        ),
    ]
