# Generated by Django 3.2.13 on 2022-08-10 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortQuestionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('company_contact_phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email заявителя')),
                ('fio', models.CharField(max_length=255, verbose_name='Фамилия Имя')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('secret', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
