# Generated by Django 2.2.1 on 2022-07-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220703_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='company_deploy',
            field=models.TextField(blank=True, default='', verbose_name='Есть ли собственные разработки (краткое описание)'),
        ),
    ]
