# Generated by Django 3.2.13 on 2022-08-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shortquestionaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='short_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.shortquestionaire', verbose_name='Начальная заявка'),
        ),
        migrations.AddField(
            model_name='shortquestionaire',
            name='secret_used',
            field=models.BooleanField(default=False, verbose_name='Секретный код использован'),
        ),
    ]
