# Generated by Django 3.2.13 on 2022-08-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220810_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='option',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='YesNo',
        ),
    ]
