# Generated by Django 3.2.13 on 2022-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220810_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaire',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_amount',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_can_have_dealer_page',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_ceo_has_tech',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_contact_phone',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_contact_position',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_deploy',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_destination',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_different_services',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_percent',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_regions',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_site',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='company_targeting',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='email',
        ),
        migrations.AddField(
            model_name='questionaire',
            name='short_opisanie',
            field=models.TextField(default=0, verbose_name='Краткое описание Вашего бизнеса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionaire',
            name='skolko_na_rynke',
            field=models.TextField(default=0, verbose_name='Сколько лет на рынке\\ из них на рынке автоматизации?'),
            preserve_default=False,
        ),
    ]
