# Generated by Django 2.2.1 on 2022-07-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220703_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='company_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Какой процент от Вашего оборота (из 100%)'),
        ),
    ]
