# Generated by Django 3.2.13 on 2022-08-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220810_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='short_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.shortquestionaire', verbose_name='Начальная заявка'),
        ),
    ]
